#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Jackpotter.Resource", IsApplication=true)]

namespace Jackpotter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int Luck4LifeButton = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int cash5Button = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int megamillsButton = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int pick3Button = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int pick4Button = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int powerballButton = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int button_cancel = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int button_cash5 = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int button_login = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int button_lucky4life = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int button_megamillions = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int button_pick = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int button_pick3 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int button_pick4 = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int button_powerball = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int button_reset = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
